const $ = (s, root = document) => root.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
 grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',
 folder:'M3 7V5h6l2 2h10v13H3z', play:'m8 5 11 7-11 7z', book:'M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1v15',
 chart:'M4 3v17h17M8 15v-4M13 15V7M18 15v-7', file:'M6 3h8l4 4v14H6zM14 3v5h5M9 12h6M9 16h6',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',
 plus:'M12 5v14M5 12h14', arrow:'M5 12h14m-5-5 5 5-5 5', check:'m5 12 4 4L19 6', chevron:'m9 5 7 7-7 7', down:'m6 9 6 6 6-6',
 search:'M11 3a8 8 0 1 0 0 16 8 8 0 0 0 0-16m6 14 4 4', clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 4v5l3 2',
 spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z', node:'M5 4h4v4H5zM15 4h4v4h-4zM10 16h4v4h-4zM7 8v4h10V8M12 12v4',
 shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zm-4 9 3 3 5-6', download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',
 stop:'M6 6h12v12H6z', retry:'M4 9a8 8 0 1 1 0 7M4 3v6h6', trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',
 link:'m10 14 4-4M9 7l2-2a5 5 0 0 1 7 7l-2 2M15 17l-2 2a5 5 0 0 1-7-7l2-2', chat:'M3 4h18v13H8l-5 4zM7 8h10M7 12h7',
 menu:'M4 6h16M4 12h16M4 18h16', logout:'M10 4H4v16h6M10 12h11m-4-4 4 4-4 4', user:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 21v-2a8 8 0 0 1 16 0v2',
 database:'M3 6c0-5 18-5 18 0s-18 5-18 0m0 0v12c0 5 18 5 18 0V6M3 12c0 5 18 5 18 0', info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 7v7m0-11v1',
 eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12m10-3a3 3 0 1 0 0 6 3 3 0 0 0 0-6', archive:'M3 3h18v5H3zM5 8v13h14V8M9 12h6',
};
const icon = (name, extra = '') => `<svg class="icon ${extra}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.node}"/></svg>`;
const roles = [ ['planner','规划师','问题拆解与计划','node'], ['researcher','研究员','检索与原文阅读','search'], ['analyst','分析师','证据提取与比较','book'], ['experimenter','实验员','执行可复现基准','chart'], ['reviewer','评审员','核对证据与返工','shield'], ['writer','撰稿人','综合报告与交付','file'] ];
const labels = {queued:'排队中',running:'运行中',completed:'已完成',failed:'运行失败',cancelled:'已取消',awaiting_approval:'待审批',pending:'待审批',approved:'已批准',rejected:'已拒绝',demo:'演示模式',live:'真实模式'};
const badge = status => `<span class="badge ${esc(status)}">${esc(labels[status] || status)}</span>`;
const date = ts => new Date(ts * 1000).toLocaleString('zh-CN', {month:'2-digit', day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
const ago = ts => { const minutes = Math.max(0, Math.floor((Date.now()/1000-ts)/60)); return minutes < 1 ? '刚刚' : minutes < 60 ? `${minutes} 分钟前` : minutes < 1440 ? `${Math.floor(minutes/60)} 小时前` : `${Math.floor(minutes/1440)} 天前`; };
const S = {user:null,overview:null,settings:null,project:null,run:null,projectId:'',events:[],generation:0,authMode:'login'};
let pollTimer, toastTimer;
async function api(path, method = 'GET', body) {
  const response = await fetch('/api' + path, {method, headers: body ? {'Content-Type':'application/json'} : {}, body: body ? JSON.stringify(body) : undefined});
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
  return data;
}
function toast(message, error=false) { const el=$('#toast'); el.textContent=message; el.className='show'+(error?' error':''); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.className='',4200); }
function go(route) { if(location.hash === '#'+route) load(); else location.hash=route; }
const route = () => (location.hash.slice(1) || '/overview').split('/').filter(Boolean);
function heading(title, subtitle='', actions='', eyebrow='RESEARCH WORKSPACE') { return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${esc(title)}</h1><p class="subheading">${esc(subtitle)}</p></div><div class="actions">${actions}</div></div>`; }
function button(text, action, type='', ic='plus', attrs='') { return `<button type="button" class="btn ${type}" data-action="${action}" ${attrs}>${icon(ic)}${text}</button>`; }
function empty(title, description, action='') { return `<div class="empty"><div class="empty-symbol">${icon('node')}</div><h3>${title}</h3><p>${description}</p>${action}</div>`; }
function panel(title, body, action='', note='') { return `<section class="panel"><div class="panel-header"><h2>${title}</h2>${action}</div>${body}${note?`<div class="panel-note">${icon('info')}${note}</div>`:''}</section>`; }
function visual() { return `<svg viewBox="0 0 330 200" fill="none" aria-label="资料经由 agent 汇聚为研究结论"><path d="M50 66C110 66 102 100 162 100M50 143C110 143 110 100 162 100M185 100c50 0 45-48 100-48M185 100c50 0 45 48 100 48" stroke="#b6c6a2" stroke-width="1.4" stroke-dasharray="4 5"/><rect x="19" y="37" width="63" height="51" rx="9" fill="#f8fbf2" stroke="#ccd9b9"/><path d="M34 52h26M34 60h34M34 68h19" stroke="#a9ba95" stroke-width="2"/><rect x="24" y="117" width="65" height="51" rx="9" fill="#f8fbf2" stroke="#ccd9b9"/><path d="M39 153v-15m10 15v-23m10 23v-12m10 12v-28" stroke="#a0b48a" stroke-width="4"/><circle cx="172" cy="100" r="40" stroke="#c2d2ad" stroke-dasharray="3 5"/><rect x="143" y="71" width="58" height="58" rx="17" fill="#315b40"/><path d="m172 83 5 12 12 5-12 5-5 12-5-12-12-5 12-5z" fill="#d6eda8"/><rect x="260" y="29" width="54" height="48" rx="9" fill="#f8fbf2" stroke="#ccd9b9"/><path d="m276 53 7 7 12-15" stroke="#98b27d" stroke-width="2"/><rect x="254" y="126" width="65" height="48" rx="9" fill="#f8fbf2" stroke="#ccd9b9"/><path d="M269 140h34M269 148h24M269 156h29" stroke="#acbd97" stroke-width="2"/><circle cx="118" cy="37" r="3" fill="#c6d4b2"/><circle cx="228" cy="166" r="3" fill="#c6d4b2"/></svg>`; }
function shell(html, active='overview', breadcrumb='概览') {
 const nav=[['overview','grid','工作台'],['projects','folder','研究项目'],['runs','node','任务中心'],['library','book','资料库'],['experiments','chart','实验结果'],['reports','file','交付报告']];
 const approvals = S.overview?.approvals.length || 0;
 $('#app').innerHTML=`<div class="layout"><aside class="sidebar"><a class="brand" href="#/overview"><span class="logo-mark">R</span><div><b>ResearchOps</b><small>研 流 · AGENT WORKSPACE</small></div></a><div class="workspace-label">YOUR RESEARCH SPACE</div><nav class="nav">${nav.map(([key,ic,title])=>`<a class="${key===active?'active':''}" href="#/${key}">${icon(ic)}${title}${key==='runs'&&approvals?`<span class="count">${approvals}</span>`:''}</a>`).join('')}</nav><div class="nav-divider"></div><nav class="nav"><a class="${active==='settings'?'active':''}" href="#/settings">${icon('settings')}工作台设置</a></nav><div class="sidebar-bottom"><div class="workspace-card"><div class="flex">${icon('spark')}从一个好问题开始</div><p>让专职 agent 完成检索、验证、评审与交付。</p>${button('创建研究项目','new-project','','plus')}</div><div class="sidebar-footer"><span>RESEARCH, WITH EVIDENCE.</span><span>v1.0</span></div></div></aside><div class="main-shell"><header class="topbar"><div class="flex"><button class="mobile-menu" data-action="menu" aria-label="打开菜单">${icon('menu')}</button><div class="breadcrumbs">个人工作空间 ${icon('chevron')} <strong>${esc(breadcrumb)}</strong></div></div><div class="top-actions"><span class="health"><i class="live-dot"></i>数据库已连接</span><button class="user-menu" data-action="account"><div class="avatar">${esc(S.user.name.slice(0,1).toUpperCase())}</div><span>${esc(S.user.name)}</span>${icon('down')}</button></div></header><main class="page">${html}<div class="footer-note">ResearchOps · 从证据到决策，每一步都可追溯</div></main></div></div>`;
}
function runRow(r) { return `<a class="run-row" href="#/run/${esc(r.id)}"><div class="run-avatar">${icon(r.status==='completed'?'file':'node')}</div><div class="run-row-content"><div class="run-row-title">${esc(r.project_name || r.goal)}</div><div class="run-row-meta"><span>${esc(roles.find(x=>x[0]===r.stage)?.[1]||r.stage)}</span><span>·</span><span>${ago(r.created)}</span><span>· ${r.mode==='demo'?'演示':'真实模型'}</span></div></div>${badge(r.status)}${icon('chevron')}</a>`; }
function metric(title, value, note, ic) {return `<div class="metric"><div class="metric-top">${title}<span class="metric-icon">${icon(ic)}</span></div><strong>${value}</strong><small>${note}</small></div>`;}
function overview() {
 const o=S.overview,active=o.runs.filter(r=>['queued','running'].includes(r.status)).length;
 const days=Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-6+i);return {label:(d.getMonth()+1)+'.'+d.getDate(),count:o.runs.filter(r=>new Date(r.created*1000).toDateString()===d.toDateString()).length};});
 const max=Math.max(1,...days.map(d=>d.count));
 shell(heading('研究工作台','从一个问题出发，让每一步研究都有据可循。',button('新建研究','new-project','','plus'),'OVERVIEW / 概览')+
 `<div class="hero"><div class="hero-copy"><div class="eyebrow">YOUR AUTONOMOUS RESEARCH TEAM</div><h1>让研究，从问题走向证据。</h1><p>6 位专职 agent，协作完成技术调研、基准验证与报告交付。你掌握方向，也能看见每一个判断。</p><div class="actions">${button('开启一项研究','new-project','','arrow')}${button('体验完整示例','demo','secondary','play')}</div></div><div class="hero-visual">${visual()}</div></div>`+
 `<div class="metrics">${metric('研究项目',o.projects.filter(p=>!p.archived).length,'独立管理问题、资料与研究历史','folder')}${metric('运行中的任务',active,`${o.approvals.length} 项等待实验审批`,'node')}${metric('证据资料',o.projects.reduce((n,p)=>n+p.source_count,0),'可回溯至任务启动时的原文快照','book')}${metric('已交付研究',o.stats.completed||0,`${o.stats.calls||0} 次模型调用 · ${(o.stats.tokens||0).toLocaleString()} tokens`,'file')}</div>`+
 (o.approvals.length?`<div class="notice">${icon('shield')}<p>有 <b>${o.approvals.length}</b> 项研究已准备好实验方案，正在等待你的决策。</p><a class="btn secondary small" href="#/run/${o.approvals[0].id}">查看方案 ${icon('arrow')}</a></div>`:'')+
 `<div class="grid-main"><div>${panel('最近的研究任务',o.runs.length?`<div class="row-list">${o.runs.slice(0,4).map(runRow).join('')}</div>`:empty('研究，从这里开始','创建项目并导入资料，或用示例项目体验一次完整的研究闭环。',button('载入示例项目','demo','secondary','play')),`<a class="text-link" href="#/runs">全部任务 ${icon('arrow')}</a>`)}
 ${panel('你的 agent 团队',`<div class="agent-path">${roles.map(([key,name,description,ic],i)=>`<div class="agent-tile"><span class="agent-num">0${i+1}</span>${icon(ic)}<h4>${name} <span class="muted">/ ${key}</span></h4><p>${description}</p></div>`).join('')}</div>`,'<span class="badge">6 ROLES</span>','共享证据 · 工具权限隔离 · 评审反馈回路')}</div><div>
 ${panel('研究活动',`<div class="panel-body"><div class="flex"><span style="font-size:30px">${days.reduce((n,d)=>n+d.count,0)}</span><small class="muted">近 7 天发起的任务</small></div><div class="mini-chart">${days.map(d=>`<div class="day"><div class="day-bar" style="height:${Math.max(3,d.count/max*100)}%" title="${d.label}：${d.count} 项"></div><span>${d.label}</span></div>`).join('')}</div><div class="chart-caption"><span><i class="legend-dot"></i>任务数量</span><span>最近 100 个任务</span></div></div>`)}
 ${panel('研究闭环',`<div class="panel-body"><div class="eyebrow">EVIDENCE FIRST</div><h3 style="line-height:1.8;margin-bottom:12px">先让证据站得住，<br>再让结论向前走。</h3><p class="muted" style="font-size:11px">每次执行保留原文引用、工具结果与决策记录。实验审批后运行，评审未通过时返回分析阶段。</p><div style="margin-top:18px"><a class="text-link" href="#/settings">配置你的模型服务 ${icon('arrow')}</a></div></div>`)}</div></div>`);
}
function projects() {const items=S.overview.projects;shell(heading('研究项目','按目标组织资料、数据与 agent 任务。',button('新建项目','new-project'),'PROJECTS / 项目')+`<div class="toolbar"><div class="search">${icon('search')}<input id="project-search" placeholder="搜索项目或研究问题" aria-label="搜索项目"></div><span class="muted" style="font-size:11px">${items.length} 个项目</span></div><div class="project-grid">${items.map(p=>`<a class="project-card searchable" data-search="${esc((p.name+p.question).toLowerCase())}" href="#/project/${p.id}"><div class="project-card-top"><span class="project-icon">${icon('folder')}</span><span class="badge">${p.archived?'已归档':'研究空间'}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.question)}</p><div class="project-card-footer"><span>${icon('book')}${p.source_count} 份资料</span><span>${p.run_count} 次研究 ${icon('arrow')}</span></div></a>`).join('')}</div>`+(items.length?'':empty('创建第一个研究项目','输入你想解决的问题，建立专属研究空间。',button('创建项目','new-project'))),'projects','研究项目');}
function runs() { const items=S.overview.runs;shell(heading('任务中心','查看执行状态、审批实验、从检查点重试失败任务。','','RUNS / 任务')+`<div class="toolbar"><div class="search">${icon('search')}<input id="run-search" placeholder="搜索研究目标" aria-label="搜索任务"></div><select class="filter-select" id="status-filter" aria-label="筛选任务状态"><option value="">全部状态</option>${Object.entries(labels).filter(([k])=>!['demo','live','pending','approved','rejected'].includes(k)).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div>`+panel('全部任务',items.length?`<div class="table-wrap"><table><thead><tr><th>研究目标</th><th>模式</th><th>当前阶段</th><th>状态</th><th>创建时间</th><th></th></tr></thead><tbody>${items.map(r=>`<tr class="searchable" data-search="${esc((r.goal+r.project_name).toLowerCase())}" data-status="${r.status}"><td class="title"><a href="#/run/${r.id}">${esc(r.project_name)}</a><p class="subheading">${esc(r.goal.slice(0,75))}</p></td><td>${badge(r.mode)}</td><td>${esc(roles.find(x=>x[0]===r.stage)?.[1])}</td><td>${badge(r.status)}</td><td class="small">${date(r.created)}</td><td><a class="text-link" href="#/run/${r.id}">打开 ${icon('arrow')}</a></td></tr>`).join('')}</tbody></table></div>`:empty('尚无任务','创建项目后即可启动研究。',button('创建项目','new-project'))),'runs','任务中心');}
function projectPicker() {return `<select class="filter-select" id="project-picker" aria-label="切换项目">${S.overview.projects.map(p=>`<option value="${p.id}" ${p.id===S.project?.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`;}
function sourceList(project) {return `<div class="toolbar"><div class="search">${icon('search')}<input id="source-search" placeholder="搜索资料标题或正文" aria-label="搜索资料"></div>${button('导入资料','import-source','secondary','plus')}</div>`+panel(`${project.sources.length} 份资料`,project.sources.length?project.sources.map(s=>`<article class="source-card searchable" data-search="${esc((s.title+s.content).toLowerCase())}"><div class="source-card-top"><div><div class="source-kind">${esc(s.kind)} · ${date(s.created)}</div><h3>${esc(s.title)}</h3></div><button class="btn ghost" data-action="delete-source" data-id="${s.id}" aria-label="删除资料">${icon('trash')}</button></div><p>${esc(s.content.slice(0,170))}${s.content.length>170?'…':''}</p><div class="source-tags">${s.metadata?.coverage==='abstract_only'?'<span class="badge">仅摘要</span>':''}${s.kind==='demo'?'<span class="badge demo">原创演示资料</span>':''}${s.url?`<a class="text-link" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${icon('link')}来源</a>`:''}</div><details><summary>查看完整原文</summary><div class="source-text">${esc(s.content)}</div></details></article>`).join(''):empty('还没有资料','支持文本、Markdown、PDF（需 PDF 扩展）；真实模式也可由研究员检索 arXiv。'),'','任务使用资料快照，之后删除资料不会改变历史报告中的引用。');}
function datasetsPanel(project) {return panel('实验数据集',project.datasets.length?`<div class="table-wrap"><table><thead><tr><th>文件名</th><th>查询数</th><th>候选行数</th><th></th></tr></thead><tbody>${project.datasets.map(d=>`<tr><td>${esc(d.name)}<div class="mono muted">${esc(d.metadata.sha256.slice(0,16))}…</div></td><td>${d.metadata.queries}</td><td>${d.metadata.rows}</td><td><button class="btn ghost" data-action="delete-dataset" data-id="${d.id}" aria-label="删除数据集">${icon('trash')}</button></td></tr>`).join('')}</tbody></table></div>`:empty('导入检索评估数据','CSV 包含 query、document、relevant 三列，可选 query_id。'),button('导入 CSV','import-dataset','secondary small','plus'),'仅执行受控检索基准；不执行模型生成的任意代码。');}
function projectPage(tab='sources') {const p=S.project;const schedule=p.schedule;
 shell(heading(p.name,p.question,button('编辑','edit-project','secondary','settings')+(!p.archived?button('启动研究','new-run','','play'):button('恢复项目','unarchive','secondary','archive')),'PROJECT / 研究空间')+
 `<div class="tabs">${[['sources','资料与数据'],['runs','研究历史'],['chat','资料问答'],['schedule','定期研究']].map(([k,v])=>`<a class="tab ${tab===k?'active':''}" href="#/project/${p.id}/${k}">${v}</a>`).join('')}</div>`+
 (tab==='runs'?panel('研究历史',p.runs.length?`<div class="row-list">${p.runs.map(runRow).join('')}</div>`:empty('尚未运行研究','导入资料后启动一次研究任务。',button('启动研究','new-run','','play'))):
 tab==='chat'?`<div class="chat-layout">${panel('资料定位与原文问答',`<div class="chat-messages" id="chat-messages"></div><form id="chat-form" class="chat-form"><input name="content" placeholder="查找资料中的概念，例如：BM25 的局限" required minlength="2" aria-label="提问"><button class="btn">${icon('arrow')}查找</button></form>`)}${panel('证据可见的回答',`<div class="panel-body"><p class="muted" style="font-size:12px">这里使用关键词检索定位原文，适合快速查证。需要模型综合分析时，启动研究任务，获得带引用和评审记录的报告。</p></div>`)}</div>`:
 tab==='schedule'?panel('定期技术追踪',`<form class="panel-body" id="schedule-form"><div class="notice info"><p>按周期创建新的证据调研任务。每次保留独立记录；定期任务不自动执行实验，且服务运行时才会调度。</p></div><div class="form-grid"><div class="field"><label for="interval">运行周期 / 小时</label><input id="interval" name="interval_hours" type="number" min="1" max="720" value="${schedule?.interval_hours||24}" required></div><div class="field"><label for="schedule-mode">执行模式</label><select id="schedule-mode" name="mode"><option value="demo">演示模式</option><option value="live" ${schedule?.mode==='live'?'selected':''}>真实模型</option></select></div></div><label class="checkbox-label"><input type="checkbox" name="enabled" ${schedule?.enabled?'checked':''}>启用定期研究</label><p class="subheading" style="margin:14px 0">${schedule?.enabled?'下一次运行：'+date(schedule.next_at):'当前未启用'}</p><button class="btn">保存设置</button></form>`):sourceList(p)+datasetsPanel(p)), 'projects',p.name);
 if(tab==='chat')loadMessages();
}
async function loadMessages() { const items=await api(`/projects/${S.project.id}/messages`);const el=$('#chat-messages');if(el){el.innerHTML=items.length?items.map(m=>`<div class="message ${m.role}"><small>${m.role==='user'?'你':'资料助手 · 原文定位'}</small>${esc(m.content)}</div>`).join(''):empty('向你的资料提问','根据关键词返回相关原文，方便核查。');el.scrollTop=el.scrollHeight;} }
function library() {shell(heading('证据资料库','管理研究的输入，保留每一条结论的出处。',projectPicker(),'LIBRARY / 资料')+sourceList(S.project)+datasetsPanel(S.project),'library','资料库');}
function workflow(r) {const done=new Set(r.steps.filter(s=>s.status==='completed').map(s=>s.role));return `<div class="flow-grid">${roles.map(([key,name,description,ic],i)=>{const isDone=done.has(key),current=r.stage===key&&['running','awaiting_approval'].includes(r.status);return `<div class="flow-node ${isDone?'complete':''} ${current?'current':''}"><div class="top"><span class="stage-no">0${i+1}</span>${isDone?icon('check'):current?badge(r.status):icon(ic)}</div><h3>${name} <span class="muted">/ ${key}</span></h3><p>${key==='experimenter'&&r.state.experiment_skipped?'本次已跳过实验':description}</p></div>`;}).join('')}</div>`;}
function approvalBanner(r) {if(r.status!=='awaiting_approval')return '';const a=r.approval?.request;return `<div class="notice">${icon('shield')}<div class="spacer"><h3>实验方案已准备就绪</h3><p style="margin-top:6px">${esc(a?.dataset)} · ${esc(a?.methods.join(' / '))} · K=${a?.k}<br>${esc(a?.scope)}</p></div><div class="actions">${button('查看并审批','review-approval','','check')}</div></div>`;}
function eventLog(events) {return events.length?`<div class="timeline">${events.map(e=>`<details class="event" data-event-id="${e.id}" data-kind="${esc(e.kind)}"><summary><span class="role">${esc(e.role||'orchestrator')}</span><span>${esc(e.message)}</span><span class="time">${new Date(e.created*1000).toLocaleTimeString('zh-CN',{hour12:false})}</span></summary><pre>${esc(JSON.stringify(e.data,null,2))}</pre></details>`).join('')}</div>`:empty('等待工作进程','任务开始后，每一次工具调用都会记录在这里。');}
function graph(r) {
 const claims=r.state.analyst?.claims||[];if(!claims.length)return empty('证据图谱尚未生成','分析师完成后，可以查看“资料 → 论点 → 报告”的引用关系。');
 const used=[...new Set(claims.map(c=>c.source_id))],sources=used.map(id=>r.sources.find(s=>s.id===id));
 const h=Math.max(300,Math.max(sources.length,claims.length)*68+70),sy=i=>55+i*68,cy=i=>55+i*68;
 const lines=claims.map((c,i)=>`<path d="M210 ${sy(used.indexOf(c.source_id))}C270 ${sy(used.indexOf(c.source_id))} 275 ${cy(i)} 335 ${cy(i)}" stroke="#ccd9bd" fill="none"/><path d="M545 ${cy(i)}C600 ${cy(i)} 620 ${h/2} 666 ${h/2}" stroke="#d8e2cc" fill="none"/>`).join('');
 const nodes=sources.map((s,i)=>`<g class="graph-node" data-action="focus-source" data-id="${esc(s.id)}" role="button" tabindex="0" aria-label="查看来源 ${esc(s.title)}"><title>${esc(s.title)}</title><rect x="15" y="${sy(i)-21}" width="195" height="42" rx="7" fill="#fff" stroke="#dce5d0"/><text x="29" y="${sy(i)+4}" fill="#758a62" font-size="11">${esc(s.title.slice(0,16))}${s.title.length>16?'…':''}</text></g>`).join('')+claims.map((c,i)=>`<g class="graph-node" data-action="focus-claim" data-index="${i}" role="button" tabindex="0" aria-label="查看论点 ${i+1}"><title>${esc(c.text)}</title><rect x="335" y="${cy(i)-21}" width="210" height="42" rx="7" fill="#eff5e8" stroke="#d4e1c6"/><text x="349" y="${cy(i)+4}" fill="#61774f" font-size="11">论点 ${i+1} · ${esc(c.text.slice(0,12))}…</text></g>`).join('');
 return `<svg class="graph-canvas" viewBox="0 0 825 ${h}" role="img" aria-label="证据引用关系图"><text x="15" y="17" font-size="10" fill="#93a285">SOURCE / 来源</text><text x="335" y="17" font-size="10" fill="#93a285">CLAIM / 论点</text><text x="665" y="17" font-size="10" fill="#93a285">DELIVERY / 交付</text>${lines}${nodes}<rect x="666" y="${h/2-26}" width="140" height="52" rx="10" fill="#305740"/><text x="736" y="${h/2+5}" fill="#e5efda" font-size="13" text-anchor="middle">${r.status==='completed'?'研究报告':'待评审报告'}</text></svg><p class="subheading">点击节点查看来源与摘录。连线表示引用关系；并不自动证明语义上的支持关系。</p><div id="quote-inspector"></div>`;
}
function comparisons(r) {const rows=r.state.analyst?.comparisons||[];return rows.length?`<div class="table-wrap"><table><thead><tr><th>方法 / 主题</th><th>能力或优点</th><th>局限与适用边界</th><th>证据</th></tr></thead><tbody>${rows.map(c=>`<tr><td class="title">${esc(c.method)}</td><td>${esc(c.strength)}</td><td>${esc(c.weakness)}</td><td>${c.source_ids.map(id=>`<button class="btn secondary small" data-action="inspect-source" data-id="${id}">${icon('book')}原文</button>`).join(' ')}</td></tr>`).join('')}</tbody></table></div>`:empty('等待方法分析','分析师将根据原始资料提取可比较的方法和适用边界。');}
function benchmark(b) {if(!b)return empty('本次尚无实验结果','选择 CSV 数据集启动任务，并在实验审批后运行固定候选检索基准。');return `<div class="metrics">${metric('评估查询',b.queries,'查询级计算与重采样','search')}${metric('候选文档',b.documents,`${b.rows} 行查询—文档配对`,'book')}${metric('比较方法',b.results.length,'真实 CPU 执行结果','chart')}${metric('检索深度',b.k,'Recall@K / nDCG@K','node')}</div><div class="grid-main">${panel('方法表现',`<div class="panel-body bar-chart">${b.results.map(r=>`<div class="bar-group"><div class="bar-group-header"><b>${esc(r.method.toUpperCase())}</b><small class="muted">nDCG CI: ${r.ndcg_ci95.map(x=>x.toFixed(3)).join('–')}</small></div>${[['recall','Recall@'+b.k,''],['mrr','MRR','blue'],['ndcg','nDCG@'+b.k,'light']].map(([key,label,color])=>`<div class="bar-item"><label>${label}</label><div class="bar-track"><div class="bar-fill ${color}" style="width:${r[key]*100}%"></div></div><b>${r[key].toFixed(3)}</b></div>`).join('')}</div>`).join('')}</div>`)}${panel('实验记录',`<div class="panel-body"><div class="eyebrow">REPRODUCIBLE BY DESIGN</div><p style="font-size:12px">${esc(b.limitations)}</p><div class="field" style="margin-top:22px"><label>数据 SHA-256</label><div class="setting-code mono">${esc(b.dataset_sha256)}</div></div><p class="subheading">${esc(b.protocol)}<br>固定种子：${b.seed}<br>MRR 基于全候选排序。并列打分由文档内容哈希确定。</p></div>`)}</div>`+panel('逐查询指标',`<div class="table-wrap"><table><thead><tr><th>方法</th><th>查询</th><th>Recall@${b.k}</th><th>MRR</th><th>nDCG@${b.k}</th></tr></thead><tbody>${b.results.flatMap(r=>r.per_query.map(q=>`<tr><td class="mono">${esc(r.method)}</td><td>${esc(q.query)}</td><td>${q.recall.toFixed(4)}</td><td>${q.mrr.toFixed(4)}</td><td>${q.ndcg.toFixed(4)}</td></tr>`)).join('')}</tbody></table></div>`);}
function markdown(text) {
 const lines=text.split('\n');let out='',inList=false;
 const inline=s=>esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
 for(let i=0;i<lines.length;i++){const line=lines[i];if(!line.startsWith('- ')&&inList){out+='</ul>';inList=false;}
  if(line.startsWith('|')&&lines[i+1]?.match(/^\|[-: |]+\|$/)){const cells=s=>s.split(/(?<!\\)\|/).slice(1,-1).map(x=>inline(x.trim().replace(/\\\|/g,'|')));out+='<div class="table-wrap"><table><thead><tr>'+cells(line).map(x=>`<th>${x}</th>`).join('')+'</tr></thead><tbody>';i+=2;while(i<lines.length&&lines[i].startsWith('|')){out+='<tr>'+cells(lines[i]).map(x=>`<td>${x}</td>`).join('')+'</tr>';i++;}out+='</tbody></table></div>';i--;}
  else if(line.startsWith('# '))out+=`<h1>${inline(line.slice(2))}</h1>`;else if(line.startsWith('## '))out+=`<h2>${inline(line.slice(3))}</h2>`;else if(line.startsWith('### '))out+=`<h3>${inline(line.slice(4))}</h3>`;else if(line.startsWith('- ')){if(!inList){out+='<ul>';inList=true;}out+=`<li>${inline(line.slice(2))}</li>`;}else if(line.trim())out+=`<p>${inline(line)}</p>`;
 }return out+(inList?'</ul>':'');
}
function runPage(tab='trace') {const r=S.run,complete=new Set(r.steps.filter(s=>s.status==='completed').map(s=>s.role)).size;
 const actions=(['queued','running','awaiting_approval'].includes(r.status)?button('取消任务','cancel-run','secondary','stop'):['failed','cancelled'].includes(r.status)?button('从检查点重试','retry-run','secondary','retry'):'')+(r.artifacts.length?`<a class="btn" href="/api/runs/${r.id}/export">${icon('download')}导出产物</a>`:'');
 let body='';
 if(tab==='evidence')body=panel('证据引用图谱',`<div class="panel-body">${graph(r)}</div>`);
 else if(tab==='comparison')body=panel('方法与边界',comparisons(r));
 else if(tab==='experiment')body=benchmark(r.state.benchmark);
 else if(tab==='report')body=S.report?`<div class="report">${markdown(S.report)}</div>`:empty('报告尚未交付','完成证据分析、实验决策与评审后，撰稿 agent 将生成最终报告。');
 else body=`<div class="run-layout"><div>${panel('协作流程',`<div class="panel-body">${workflow(r)}</div>`,badge(r.status),`规划 → 检索 → 分析 → 实验决策 → 评审 → 交付 · 已返工 ${r.state._revision||0} 次`)}${panel('执行轨迹',eventLog(S.events),'<span class="badge">持久化事件记录</span>')}</div><aside class="run-side">${panel('任务信息',`<div class="side-info"><div class="flex">${badge(r.mode)}<span class="mono muted">${r.id.slice(-8)}</span></div><div class="progress-line"><span style="width:${complete/6*100}%"></span></div><small class="muted">${complete} / 6 个角色已执行</small><dl><div><dt>开始时间</dt><dd>${date(r.created)}</dd></div><div><dt>模型</dt><dd>${r.mode==='demo'?'确定性演示策略':esc(r.config.model)}</dd></div><div><dt>调用次数</dt><dd>${r.calls} / ${r.config.max_calls}</dd></div><div><dt>输入 / 输出 tokens</dt><dd>${r.input_tokens} / ${r.output_tokens}</dd></div><div><dt>引用资料</dt><dd>${r.sources.length} 份快照</dd></div><div><dt>实验数据</dt><dd>${esc(r.config.dataset?.name||'未选择')}</dd></div></dl></div>`)}${panel('交付文件',r.artifacts.length?`<div class="panel-body">${r.artifacts.map(a=>`<a class="run-row" href="/api/artifacts/${a.id}" style="font-size:11px">${icon('file')}<span class="spacer">${esc(a.name)}</span>${icon('download')}</a>`).join('')}</div>`:empty('等待交付','报告、证据、指标与可复现数据将出现在这里。'))}</aside></div>`;
 shell(heading('研究执行空间',r.goal,actions,'RUN / '+r.id.slice(-8).toUpperCase())+approvalBanner(r)+(r.error?`<div class="notice error">${icon('info')}<p>${esc(r.error)}</p></div>`:'')+(r.mode==='demo'?`<div class="notice info">${icon('info')}<p>演示模式使用明确的策略模拟 agent 决策；工具、数据库、审批与实验真实运行。接入模型后可使用真实 agent 模式。</p></div>`:'')+`<div class="tabs">${[['trace','运行轨迹'],['evidence','证据图谱'],['comparison','方法比较'],['experiment','实验结果'],['report','研究报告']].map(([k,v])=>`<a class="tab ${tab===k?'active':''}" href="#/run/${r.id}/${k}">${v}</a>`).join('')}</div>`+body,'runs','研究执行空间');
}
function resultsPage(type) {const isReport=type==='reports';const runs=S.overview.runs.filter(r=>r.status==='completed');shell(heading(isReport?'交付报告':'实验与验证',isReport?'带证据引用、方法比较和实测结果的研究交付。':'从具体任务查看实测指标与可复现数据。','',isReport?'DELIVERABLES / 报告':'EXPERIMENTS / 实验')+panel(isReport?'研究交付':'已完成的研究',runs.length?`<div class="row-list">${runs.map(r=>`<a class="run-row" href="#/run/${r.id}/${isReport?'report':'experiment'}"><div class="run-avatar">${icon(isReport?'file':'chart')}</div><div class="run-row-content"><div class="run-row-title">${esc(r.project_name)}</div><div class="run-row-meta">${date(r.updated)} · ${r.mode==='demo'?'演示':'真实模型'} · ${esc(r.goal.slice(0,48))}</div></div>${icon('arrow')}</a>`).join('')}</div>`:empty('等待第一份研究成果','从示例项目开始，完成审批后即可查看报告与实验结果。',button('载入示例','demo','secondary','play'))),type,isReport?'交付报告':'实验结果');}
function settingsPage() {const s=S.settings,admin=S.user.role==='admin';shell(heading('工作台设置','配置模型服务与执行预算，管理工作空间成员。','','SETTINGS / 设置')+`<div class="settings-grid"><div>${panel('模型与 agent 配置',`<form id="settings-form" class="panel-body"><div class="field"><label for="base-url">OpenAI 兼容 API Base URL</label><input id="base-url" name="base_url" value="${esc(s.base_url)}" required ${!admin?'disabled':''}><small>以 /v1 结尾的服务地址，例如本地 Ollama 或兼容工具调用的云端服务。</small></div><div class="field"><label for="model">模型名称</label><input id="model" name="model" value="${esc(s.model)}" required ${!admin?'disabled':''}></div><div class="form-grid"><div class="field"><label for="max-calls">单任务调用上限</label><input id="max-calls" type="number" min="8" max="256" name="max_calls" value="${s.max_calls}" ${!admin?'disabled':''}></div><div class="field"><label for="max-tokens">单次输出 token 上限</label><input id="max-tokens" type="number" min="500" max="16000" name="max_output_tokens" value="${s.max_output_tokens}" ${!admin?'disabled':''}></div></div><label class="checkbox-label" style="margin:20px 0"><input name="allow_arxiv" type="checkbox" ${s.allow_arxiv?'checked':''} ${!admin?'disabled':''}>允许 agent 检索 arXiv 摘要</label>${admin?'<button class="btn">保存配置</button>':'<p class="subheading">此配置由管理员维护</p>'}<p class="subheading">配置用于新任务；已有任务保留启动时的模型与预算快照。</p></form>`)}${admin?panel('工作空间成员','<div id="users-table"></div>',button('添加成员','add-user','secondary small','plus')):''}</div><div>${panel('连接状态',`<div class="side-info"><dl><div><dt>数据库</dt><dd>SQLite / WAL</dd></div><div><dt>模型 API Key</dt><dd>${badge(s.key_configured?'approved':'pending')}</dd></div><div><dt>PDF 解析扩展</dt><dd>${s.pdf_available?'已安装':'未安装'}</dd></div><div><dt>当前权限</dt><dd>${admin?'管理员':'成员'}</dd></div></dl><p class="subheading">各成员的项目、资料、报告相互隔离；管理员可配置全局模型服务。</p></div>`)}${panel('服务端配置',`<div class="panel-body"><p class="muted" style="font-size:12px;margin-bottom:15px">密钥通过服务端环境变量读取，不写入数据库，也不返回浏览器。</p><div class="setting-code mono">export LLM_API_KEY="你的密钥"<br>python -m backend.server</div><p class="subheading" style="margin-top:18px">本地模型服务可不设密钥。真实模型需要支持工具调用和 JSON 输出。演示模式始终可离线运行。</p></div>`)}</div></div>`,'settings','工作台设置');if(admin)loadUsers();}
async function loadUsers(){const users=await api('/admin/users');const el=$('#users-table');if(el)el.innerHTML=`<div class="table-wrap"><table><thead><tr><th>成员</th><th>邮箱</th><th>权限</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.role==='admin'?'管理员':'成员'}</td></tr>`).join('')}</tbody></table></div>`;}
function field(label, name, value='', type='text', extra='') { return `<div class="field"><label for="f-${name}">${label}</label>${type==='textarea'?`<textarea id="f-${name}" name="${name}" ${extra}>${esc(value)}</textarea>`:`<input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}>`}</div>`; }
function modal(title, body, kind='', submit='保存', footer='') {$('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${title}</h2><button class="close" data-action="close" aria-label="关闭">×</button></div><form id="modal-form" data-kind="${kind}"><div class="modal-content"><div class="modal-error" id="modal-error"></div>${body}</div><div class="modal-footer">${footer}${button('取消','close','secondary','stop')}${kind?`<button type="submit" class="btn" id="modal-save">${submit}</button>`:''}</div></form></section></div>`;$('#modal-root input, #modal-root textarea, #modal-root button')?.focus();}
function closeModal() {$('#modal-root').innerHTML='';}
function newRunModal() {const p=S.project;modal('启动一项研究',field('本次研究目标','goal',p.question,'textarea','required minlength="5" maxlength="4000"')+`<div class="form-grid"><div class="field"><label for="f-mode">执行模式</label><select id="f-mode" name="mode"><option value="demo">演示策略（无需密钥）</option><option value="live">真实模型 agent</option></select></div><div class="field"><label for="f-dataset">实验数据集</label><select id="f-dataset" name="dataset_id"><option value="">仅调研，不执行实验</option>${p.datasets.map((d,i)=>`<option value="${d.id}" ${i===0?'selected':''}>${esc(d.name)}</option>`).join('')}</select></div></div>`+field('检索评估 K','k','3','number','min="1" max="20" required')+`<div class="notice info"><p>实验比较 overlap / TF-IDF / BM25，执行前将展示方案供你审批。真实模式由模型自主选择检索词、调用工具、分析与评审。</p></div>`,'new-run','启动研究');}
function inspectSource(id) {const s=(S.run?.sources||S.project?.sources||[]).find(x=>x.id===id);if(!s)return;modal('查看证据原文',`<h3>${esc(s.title)}</h3><p class="subheading">${esc(s.kind)}${s.url?` · <a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">查看来源</a>`:''}</p><div class="source-text" style="white-space:pre-wrap;line-height:1.9;font-size:12px;margin-top:20px">${esc(s.content)}</div>`);}
async function action(name, el) {
 if(name==='close')return closeModal();
 if(name==='menu')return $('.sidebar')?.classList.toggle('open');
 if(name==='new-project')return modal('创建研究项目',field('项目名称','name','','text','required maxlength="120" placeholder="例如：企业知识库检索选型"')+field('你希望解决什么问题？','question','','textarea','required minlength="5" maxlength="4000" placeholder="明确研究目标、决策背景和你关心的约束…"')+field('项目描述（可选）','description','','textarea','maxlength="2000"'),'new-project','创建项目');
 if(name==='demo'){el.disabled=true;const p=await api('/demo','POST',{});const r=await api(`/projects/${p.id}/runs`,'POST',{mode:'demo',dataset_id:p.dataset_id});toast('示例已载入，研究任务正在运行');return go('/run/'+r.id);}
 if(name==='new-run')return newRunModal();
 if(name==='edit-project')return modal('编辑项目',field('项目名称','name',S.project.name,'text','required maxlength="120"')+field('研究问题','question',S.project.question,'textarea','required minlength="5" maxlength="4000"'),'edit-project','保存',button(S.project.archived?'删除项目':'归档项目',S.project.archived?'delete-project':'archive','danger','archive'));
 if(name==='archive'||name==='unarchive'){await api('/projects/'+S.project.id,'PATCH',{archived:name==='archive'});closeModal();toast(name==='archive'?'项目已归档':'项目已恢复');return load();}
 if(name==='delete-project'){if(!confirm('永久删除此项目及其任务、资料与报告？'))return;await api('/projects/'+S.project.id,'DELETE');closeModal();S.projectId='';return go('/projects');}
 if(name==='import-source')return modal('导入研究资料',field('标题','title','','text','required maxlength="300"')+field('来源链接（可选）','url','','url','placeholder="https://…"')+field('原文内容','content','','textarea','maxlength="60000" placeholder="粘贴论文摘要、技术文档或研究笔记；也可选择下方文件"')+`<div class="dropzone">${icon('book')} 选择文本、Markdown 或 PDF<input name="source_file" type="file" accept=".txt,.md,.pdf" aria-label="选择资料文件"><p class="file-note">文本最多 60,000 字符 · PDF ≤ 1.4 MB，最多 80 页，需安装 PDF 扩展</p></div>`,'import-source','导入资料');
 if(name==='import-dataset')return modal('导入检索评估 CSV',`<div class="notice info"><p>每行是一组查询与候选文档。必需列：query、document、relevant（0/1）；可选 query_id。至少两个查询，每个查询至少两个候选及一个相关文档。</p></div>`+field('数据集名称','name','','text','required maxlength="120" placeholder="例如：真实业务查询评估集.csv"')+`<div class="dropzone">${icon('chart')} 选择 CSV 文件<input name="dataset_file" type="file" accept=".csv" required aria-label="选择 CSV 数据集"><p class="file-note">最多 3,000 行 · 文件 ≤ 1.4 MB</p></div>`,'import-dataset','校验并导入');
 if(name==='delete-source'||name==='delete-dataset'){if(!confirm('删除这条项目资料？已有任务仍保留快照。'))return;await api(`/projects/${S.project.id}/${name==='delete-source'?'sources':'datasets'}/${el.dataset.id}`,'DELETE');toast('已删除');return load();}
 if(name==='review-approval'){const a=S.run.approval.request;return modal('审批基准实验',`<div class="notice info"><p>${esc(a.scope)}</p></div><div class="field"><label>数据集</label><p>${esc(a.dataset)}</p></div><div class="field"><label>校验值</label><div class="setting-code mono">${esc(a.dataset_sha256)}</div></div><p style="font-size:12px;margin-bottom:20px">方法：${esc(a.methods.join(' / '))} · K=${a.k}</p><div class="field"><label for="f-decision">审批决定</label><select id="f-decision" name="decision"><option value="approved">批准并执行实验</option><option value="rejected">拒绝实验，继续交付证据报告</option></select></div>`+field('备注（可选）','note','','textarea','maxlength="1000"'),'approval','提交决定');}
 if(name==='cancel-run'){if(!confirm('取消当前任务？已完成的阶段和工具记录会保留。'))return;await api(`/runs/${S.run.id}/cancel`,'POST',{});toast('已请求取消');return load();}
 if(name==='retry-run'){await api(`/runs/${S.run.id}/retry`,'POST',{});toast('已重新排队，将从检查点继续');return load();}
 if(name==='inspect-source'||name==='focus-source')return inspectSource(el.dataset.id);
 if(name==='focus-claim'){const c=S.run.state.analyst.claims[Number(el.dataset.index)],s=S.run.sources.find(x=>x.id===c.source_id);$('#quote-inspector').innerHTML=`<div class="quote-card"><h4>${esc(c.text)}</h4><p>「${esc(c.quote)}」</p><small>来源：${esc(s?.title)}</small></div>`;return;}
 if(name==='account')return modal('个人账户',field('显示名称','name',S.user.name,'text','required maxlength="80"')+`<p class="subheading">${esc(S.user.email)} · ${S.user.role==='admin'?'管理员':'成员'}</p>`,'profile','保存',button('退出登录','logout','secondary','logout'));
 if(name==='logout'){await api('/auth/logout','POST',{});S.user=null;closeModal();clearTimeout(pollTimer);return boot();}
 if(name==='add-user')return modal('添加工作空间成员',field('姓名','name','','text','required maxlength="80"')+field('邮箱','email','','email','required')+field('初始密码','password','','password','required minlength="10" maxlength="256" autocomplete="new-password"')+'<p class="subheading">新成员拥有独立的项目空间，默认不具有全局设置权限。</p>','add-user','创建成员');
 if(name==='auth-switch'){S.authMode=S.authMode==='register'?'login':'register';return authPage();}
 if(name==='reload')return load();
}
async function submitModal(form) {
 const fd=new FormData(form),v=Object.fromEntries(fd),kind=form.dataset.kind;
 if(kind==='new-project'){const p=await api('/projects','POST',v);closeModal();toast('项目已创建，接下来导入资料');return go('/project/'+p.id);}
 if(kind==='new-run'){const r=await api(`/projects/${S.project.id}/runs`,'POST',{...v,k:Number(v.k),dataset_id:v.dataset_id||null});closeModal();return go('/run/'+r.id);}
 if(kind==='edit-project'){await api(`/projects/${S.project.id}`,'PATCH',v);closeModal();return load();}
 if(kind==='import-source'){
  const file=fd.get('source_file'),data={title:v.title,url:v.url,content:v.content};
  if(file?.size){if(file.size>1400000)throw new Error('文件过大，请控制在 1.4 MB 内');if(file.name.toLowerCase().endsWith('.pdf')){const buffer=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of buffer)binary+=String.fromCharCode(b);data.pdf_base64=btoa(binary);}else data.content=await file.text();}
  await api(`/projects/${S.project.id}/sources`,'POST',data);closeModal();toast('资料已导入');return load();
 }
 if(kind==='import-dataset'){const file=fd.get('dataset_file');if(!file?.size)throw new Error('请选择非空 CSV');if(file.size>1400000)throw new Error('CSV 文件过大');await api(`/projects/${S.project.id}/datasets`,'POST',{name:v.name,content:await file.text()});closeModal();toast('CSV 校验通过，已导入');return load();}
 if(kind==='approval'){await api(`/runs/${S.run.id}/approval`,'POST',v);closeModal();toast('审批已提交，任务继续运行');return load();}
 if(kind==='profile'){S.user=await api('/profile','PATCH',v);closeModal();return load();}
 if(kind==='add-user'){await api('/admin/users','POST',v);closeModal();toast('成员已创建');return load();}
}
function authPage() {const setup=S.authMode==='setup',register=S.authMode==='register';$('#app').innerHTML=`<div class="auth-layout"><div class="auth-story"><a class="brand" href="#"><span class="logo-mark">R</span><div><b>ResearchOps</b><small>研 流 · AGENT WORKSPACE</small></div></a><div><div class="eyebrow" style="color:#bdd394">A WORKSPACE FOR CURIOUS MINDS</div><h1>好的研究，<br>始于问题。<br><em>Built on evidence.</em></h1><p>将你的研究目标交给一支专职 agent 团队。从资料检索到实验验证，让每一个结论都有可追溯的依据。</p></div>${visual()}<div class="auth-bottom">PLAN · EXPLORE · VERIFY · DELIVER</div></div><div class="auth-form-area"><form class="auth-form" id="auth-form"><div class="eyebrow">${setup?'WELCOME TO RESEARCHOPS':'YOUR RESEARCH CONTINUES'}</div><h2>${setup?'创建你的工作空间':register?'创建账户':'欢迎回来'}</h2><p class="subheading">${setup?'设置首个管理员账户，开始你的第一项研究。':register?'建立独立的个人研究空间。':'登录，继续你的研究与发现。'}</p><div class="auth-error" id="auth-error"></div>${setup||register?field('姓名','name','','text','required maxlength="80" autocomplete="name"'):''}${field('邮箱','email','','email','required autocomplete="username"')}${field('密码','password','','password',`required ${setup||register?'minlength="10"':''} maxlength="256" autocomplete="${setup||register?'new-password':'current-password'}"`)}${setup?field('远程初始化令牌（本机访问留空）','bootstrap_token','','password','autocomplete="off"'):''}<button class="btn" type="submit">${setup?'创建工作空间':register?'注册并进入':'进入工作台'} ${icon('arrow')}</button>${!setup&&S.bootstrap.registration_enabled?`<button class="btn ghost" type="button" data-action="auth-switch">${register?'已有账户？登录':'没有账户？注册'}</button>`:''}<p class="fineprint">${setup?'密码至少 10 位，无预设账号与密码。':'账户资料与项目数据保存在你的 ResearchOps 服务中。'}<br>无需模型密钥即可体验完整演示流程。</p></form></div></div>`;}
async function boot(){S.bootstrap=await api('/bootstrap');try{S.user=await api('/me');await load();}catch{S.authMode=S.bootstrap.needs_setup?'setup':'login';authPage();}}
async function readEvents(id){let events=[],after=0;while(true){const part=await api(`/runs/${id}/events?after=${after}`);events.push(...part);if(part.length<500)return events;after=part.at(-1).id;}}
async function load(isPoll=false){
 if(!S.user)return;clearTimeout(pollTimer);const generation=++S.generation,[page,id,tab]=route(),oldScroll=window.scrollY;
 const opened=[...document.querySelectorAll('details[open][data-event-id]')].map(x=>x.dataset.eventId);
 const previousRun=S.run;
 try{
  const overviewData=await api('/overview');if(generation!==S.generation)return;S.overview=overviewData;
  if(page==='run'&&id){const [run,events]=await Promise.all([api('/runs/'+id),readEvents(id)]);if(generation!==S.generation)return;
   S.run=run;S.events=events;S.report='';if(tab==='report'){const art=run.artifacts.find(a=>a.name==='report.md');if(art)S.report=await(await fetch('/api/artifacts/'+art.id)).text();}
   if(generation!==S.generation)return;
   const unchanged=isPoll&&previousRun?.id===run.id&&previousRun.updated===run.updated&&previousRun.status===run.status;
   if(!unchanged){runPage(tab);opened.forEach(e=>{const el=$(`[data-event-id="${e}"]`);if(el)el.open=true;});}
   if(['running','queued','awaiting_approval'].includes(run.status))pollTimer=setTimeout(()=>load(true),1700);
  }else if(page==='project'||page==='library'){
   const pid=page==='project'?id:S.projectId||S.overview.projects[0]?.id;
   if(!pid){shell(heading('资料与研究空间','请先创建一个项目。')+empty('还没有项目','每个研究项目都有独立的资料库和数据集。',button('创建项目','new-project')),page==='library'?'library':'projects');return;}
   const project=await api('/projects/'+pid);if(generation!==S.generation)return;S.project=project;S.projectId=project.id;page==='library'?library():projectPage(tab);
  }else if(page==='settings'){const settings=await api('/settings');if(generation!==S.generation)return;S.settings=settings;settingsPage();}
  else if(page==='projects')projects();else if(page==='runs')runs();else if(page==='experiments'||page==='reports')resultsPage(page);else overview();
  if(isPoll)window.scrollTo(0,oldScroll);else window.scrollTo(0,0);
 }catch(e){if(generation!==S.generation)return;toast(e.message,true);if(!isPoll)shell(heading('暂时无法打开页面',e.message)+empty('数据加载失败','请检查服务是否仍在运行。',button('重试','reload','secondary','retry')));}
}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();try{await action(el.dataset.action,el);}catch(error){toast(error.message,true);el.disabled=false;}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.key==='Enter'||e.key===' ')&&e.target.matches('.graph-node')){e.preventDefault();action(e.target.dataset.action,e.target);}if(e.key==='Tab'&&$('.modal')){const els=[...$('.modal').querySelectorAll('button,input,textarea,select,a[href]')].filter(x=>!x.disabled);const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
document.addEventListener('submit',async e=>{const form=e.target;if(!['auth-form','modal-form','settings-form','schedule-form','chat-form'].includes(form.id))return;e.preventDefault();const submit=form.querySelector('[type=submit]')||form.querySelector('button:not([type=button])');if(submit)submit.disabled=true;
 try{const v=Object.fromEntries(new FormData(form));
  if(form.id==='auth-form'){S.user=await api('/auth/'+S.authMode,'POST',v);S.bootstrap.needs_setup=false;await load();}
  else if(form.id==='modal-form')await submitModal(form);
  else if(form.id==='settings-form'){await api('/settings','PUT',{...v,max_calls:Number(v.max_calls),max_output_tokens:Number(v.max_output_tokens),allow_arxiv:v.allow_arxiv==='on'});toast('配置已保存，将用于新任务');}
  else if(form.id==='schedule-form'){await api(`/projects/${S.project.id}/schedule`,'PUT',{...v,interval_hours:Number(v.interval_hours),enabled:v.enabled==='on'});toast('定期研究设置已保存');await load();}
  else if(form.id==='chat-form'){await api(`/projects/${S.project.id}/messages`,'POST',v);form.reset();await loadMessages();}
 }catch(error){const target=form.id==='auth-form'?$('#auth-error'):form.id==='modal-form'?$('#modal-error'):null;if(target)target.textContent=error.message;else toast(error.message,true);}finally{if(submit)submit.disabled=false;}});
function filter(){const query=($('#project-search')||$('#run-search')||$('#source-search'))?.value.toLowerCase()||'',status=$('#status-filter')?.value||'';document.querySelectorAll('.searchable').forEach(el=>el.hidden=!(el.dataset.search.includes(query)&&(!status||el.dataset.status===status)));}
document.addEventListener('input',e=>{if(e.target.id.endsWith('-search'))filter();});
document.addEventListener('change',async e=>{if(e.target.id==='status-filter')filter();if(e.target.id==='project-picker'){S.projectId=e.target.value;await load();}if(e.target.name==='source_file'&&e.target.files[0]&&!$('#f-title').value)$('#f-title').value=e.target.files[0].name.replace(/\.[^.]+$/,'');if(e.target.name==='dataset_file'&&e.target.files[0]&&!$('#f-name').value)$('#f-name').value=e.target.files[0].name;});
window.addEventListener('hashchange',()=>{closeModal();load();});
boot().catch(e=>{$('#app').innerHTML=`<div class="boot"><h2>服务连接失败</h2><p>${esc(e.message)}</p><p>请启动 python -m backend.server 后刷新页面。</p></div>`;});
